apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datastore
spec:
  serviceName: "datastore"
  replicas: 1
  selector:
    matchLabels:
      app: datastore
  template:
    metadata:
      labels:
        app: datastore
    spec:
      containers:
        - name: datastore
          image: datastore:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: datastore-storage
              mountPath: /var/lib/datastore
  volumeClaimTemplates:
    - metadata:
        name: datastore-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
