apiVersion: batch/v1
kind: Job
metadata:
  name: database-init
spec:
  template:
    spec:
      containers:
      - name: db-init
        image: postgres:latest
        command: ["psql", "-c", "CREATE TABLE IF NOT EXISTS logs (date TIMESTAMP, status INTEGER, message TEXT);"]
      restartPolicy: OnFailure
