apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: webchecker-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: webchecker
            image: webchecker:latest
          restartPolicy: OnFailure
